// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCalendar: typeof import("element-plus/es")["ElCalendar"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSelectV2: typeof import("element-plus/es")["ElSelectV2"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTimePicker: typeof import("element-plus/es")["ElTimePicker"];
    Footer: typeof import("./src/components/Footer/index.vue")["default"];
    Header: typeof import("./src/components/Header/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
